Repository hyeeyoung/wishboard-android, pull requests merged in 2022-01, with the labels that each got.

#26 [feat] 링크공유 아이템 등록 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemRegistrationInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/util/NumberPickerUtil.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBottomSheetDialog.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishLinkSharingViewModel.kt
  app/src/main/res/drawable/background_dialog_top_corner.xml
  app/src/main/res/layout/activity_wish_link_sharing.xml
  app/src/main/res/layout/bottom_sheet_dialog_wish.xml
  app/src/main/res/values/strings.xml
Labels: feature

#28 [feat] 홈화면 새로고침 구현
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
Labels: feature

#29 [mod] 데이터 타입 수정
  app/src/main/java/com/hyeeyoung/wishboard/model/folder/FolderItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/sign/UserInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
Labels: mod

#33 [feat] 아이템 기본 등록 구현
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemRegistrationInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
  app/src/main/res/layout/fragment_wish.xml
Labels: feature

#35 [mod] 데이터 타입 변경 및 타입 변경에 따른 포맷 적용
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/util/BindingAdapters.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
  app/src/main/res/layout/fragment_wish_item_detail.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/item_wish.xml
Labels: mod

#39 [mod] 홈조회 및 상세조회 병합에 따른 wish 아이템 data class수정 및 변경사항 적용
  app/build.gradle
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
Labels: mod

#40 [mod] CartItem data class 수정 및 변경사항 적용
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
  app/src/main/res/layout/item_cart.xml
Labels: mod

#43 [mod] BuildConfig에 BASE_URL 상수 추가 및 적용
  app/build.gradle
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
Labels: mod

#45 [feat] 장바구니 조회, 추가, 삭제 기능 구현
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItemButtonType.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
  app/src/main/res/layout/fragment_cart.xml
Labels: feature

#47 [fix] 홈 화면의 아이템 리스트에서 장바구니 버튼 활성화 상태가 업데이트되지 않는 버그 수정
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
Labels: bug

#49 [mod] WishItem에서 cartId를 cartState로 프로퍼티 이름 변경 및 홈에서 cart 버튼 클릭 시 car…
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartStateType.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
Labels: mod

#52 [mod] 수량 버튼 클릭 시마다 updateCart 요청 및 view에서 count와 price TextView가 업데이트 되도록 코드 수정
  app/src/main/java/com/hyeeyoung/wishboard/model/cart/CartItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/cart/CartRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/adapters/CartListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/cart/screens/CartFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/CartViewModel.kt
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/item_cart.xml
Labels: mod

#53 [feat] S3에 아이템 이미지 업로드 구현
  .gitignore
  amplify/.config/project-config.json
  amplify/README.md
  amplify/backend/tags.json
  amplify/cli.json
  amplify/hooks/README.md
  app/build.gradle
  app/src/main/java/com/hyeeyoung/wishboard/WishBoardApp.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/AWSS3Service.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/common/screens/GalleryImageFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishViewModel.kt
  app/src/main/res/layout/activity_wish_link_sharing.xml
Labels: feature

#55 [refactor] Wish 관련 ViewModel 리팩토링
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItemRegistrationInfo.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/common/screens/GalleryImageFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishLinkSharingActivity.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishLinkSharingViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
  app/src/main/res/layout/activity_wish_link_sharing.xml
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/layout/fragment_wish_item_detail.xml
Labels: refactoring

#57 [feat] 아이템 삭제 구현
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
  app/src/main/res/layout/fragment_wish_item_detail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#60 [refactor] WishListViewModel에서 adapter.setData()호출 및 불필요한 wishList 변수 제거
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
Labels: refactoring

#61 [chore] 아이템 삭제 요청 url 변경
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
Labels: chore

#63 [feat] 아이템 수정 구현
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/wish/WishRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/wish_item_nav_graph.xml
Labels: feature

#65 [feat] 아이템 수정 완료 후 상세조회 ui 업데이트 구현
  app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature

#66 [refactor] loadImage 함수를 적용한 리팩토링
  app/src/main/java/com/hyeeyoung/wishboard/model/wish/WishItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/util/ImageLoader.kt
  app/src/main/java/com/hyeeyoung/wishboard/util/Util.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishItemDetailFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/adapters/WishListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/list/screens/HomeFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishListViewModel.kt
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/navigation/wish_item_registration_nav_graph.xml
Labels: refactoring

#68 [feat] 폴더 추가 구현
  app/src/main/java/com/hyeeyoung/wishboard/di/RepositoryModule.kt
  app/src/main/java/com/hyeeyoung/wishboard/model/folder/FolderItem.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderAddDialogFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderAddDialogViewModel.kt
  app/src/main/res/color/selector_dialog_yes_button_text_color.xml
  app/src/main/res/drawable/selector_dialog_yes_button_background.xml
  app/src/main/res/layout/dialog_new_folder_add.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature, mod

#71 [feat] 아이템 수동 등록 내 폴더 리스트 조회 구현
  app/src/main/java/com/hyeeyoung/wishboard/MainActivity.kt
  app/src/main/java/com/hyeeyoung/wishboard/remote/RemoteService.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepository.kt
  app/src/main/java/com/hyeeyoung/wishboard/repository/folder/FolderRepositoryImpl.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/folder/adapters/FolderListAdapter.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/folder/screens/FolderListFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/view/wish/item/screens/WishBasicFragment.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/FolderViewModel.kt
  app/src/main/java/com/hyeeyoung/wishboard/viewmodel/WishItemRegistrationViewModel.kt
  app/src/main/res/layout/fragment_folder_list.xml
  app/src/main/res/layout/fragment_wish.xml
  app/src/main/res/layout/item_folder_horizontal.xml
  app/src/main/res/layout/item_folder_square.xml
  app/src/main/res/navigation/wish_item_registration_nav_graph.xml
Labels: feature
